### ISSUE TITLE
Please add my site as your friend link. OTL

### ISSUE THREAD

**Issue by tonyfloatersu** [JasonQSY/homepage#1]
my site is tonyfloatersu.github.io

**Comment by tonyfloatersu** [comment]
Thank you very much!!!

**Comment by JasonQSY** [comment]
It is recommended to go to <https://github.com/JasonQSY/blog> or <https://jasonqsy.github.io/blog/> This one is an experimental build.

**Comment by tonyfloatersu** [comment]
噫
